### ISSUE TITLE
why

### ISSUE THREAD

**Issue by tweedge** [alexdredmon/cuteuid#1]
legitimately curious ¯\\_(ツ)_/¯

**Comment by abhijitparida** [comment]
Why not ¯\\(ツ)/¯ I would use this in a personal project.

**Comment by tweedge** [comment]
Someone else asked "why" and got a response on Reddit [here](https://www.reddit.com/r/Python/comments/easisl/cuteuid_open_source_package_to_generate_cute/):

> The emoji UUIDs are just a few of the modes I wound up adding - the initial concept was to create UUID-like identifiers that incorporated 1337 words for the novelty of it.

> In that spirit, the default mode of cuteuid returns something like 3xampl3a-boy1-goa1-5ucc33dd3p7h - since it's not truly a UUID and isn't limited to the character space of A-F + 0-9, a large number of potential variations can be generated despite being comprised entirely of (1337 translated) words.

> The next mode I added was an optional hex_only parameter, which produces fewer variations (therefore a higher chance of collision) but looks more similar to an actual UUID (e.g. 0ff1c1a1-50f7-f33d-43517a73b3d1)

> Emojis were added due to 1) the simplicity of adding them to the existing generator, 2) their larger character space leading to even more possible combinations than conventional UUIDs, and 3) their (subjective) adherence to the "cute" directive in the name I'd chosen, "CuteUID."

Which is legitimate, so enjoy c:
